# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-30 16:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_auto_20170930_1330'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='forumtarget',
            options={'verbose_name': 'Forum target', 'verbose_name_plural': 'Forum targets'},
        ),
    ]
